/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/OperationSync.def

class KBENGINEPLUGINS_API EntityBaseEntityCall_OperationSyncBase : public EntityCall
{
public:
	uint16 entityComponentPropertyID;

	EntityBaseEntityCall_OperationSyncBase(uint16 ecpID, int32 eid);

	virtual ~EntityBaseEntityCall_OperationSyncBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_OperationSyncBase : public EntityCall
{
public:
	uint16 entityComponentPropertyID;

	EntityCellEntityCall_OperationSyncBase(uint16 ecpID, int32 eid);

	virtual ~EntityCellEntityCall_OperationSyncBase();
	void reportFrame(const ENTITY_DATA& arg1);
};
