/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/FrameSyncReport.def

class KBENGINEPLUGINS_API EntityBaseEntityCall_FrameSyncReportBase : public EntityCall
{
public:
	uint16 entityComponentPropertyID;

	EntityBaseEntityCall_FrameSyncReportBase(uint16 ecpID, int32 eid);

	virtual ~EntityBaseEntityCall_FrameSyncReportBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_FrameSyncReportBase : public EntityCall
{
public:
	uint16 entityComponentPropertyID;

	EntityCellEntityCall_FrameSyncReportBase(uint16 ecpID, int32 eid);

	virtual ~EntityCellEntityCall_FrameSyncReportBase();
	void reportFrame(const FS_ENTITY_DATA& arg1);
};
