/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/FrameSync.def

class KBENGINEPLUGINS_API EntityBaseEntityCall_FrameSyncBase : public EntityCall
{
public:
	uint16 entityComponentPropertyID;

	EntityBaseEntityCall_FrameSyncBase(uint16 ecpID, int32 eid);

	virtual ~EntityBaseEntityCall_FrameSyncBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_FrameSyncBase : public EntityCall
{
public:
	uint16 entityComponentPropertyID;

	EntityCellEntityCall_FrameSyncBase(uint16 ecpID, int32 eid);

	virtual ~EntityCellEntityCall_FrameSyncBase();
};
