/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"

#include "EntityCallFrameSyncReportBase.h"

// defined in */scripts/entity_defs/Avatar.def

class KBENGINEPLUGINS_API EntityBaseEntityCall_AvatarBase : public EntityCall
{
public:
	EntityBaseEntityCall_FrameSyncReportBase* componentFrameSync;

	EntityBaseEntityCall_AvatarBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_AvatarBase();
	void endOfStatistics();
	void enterStartGame();
	void registerHalls();
	void statisticalResult(uint8 arg1, float arg2);
	void weaponChanged(int32 arg1);
};

class KBENGINEPLUGINS_API EntityCellEntityCall_AvatarBase : public EntityCall
{
public:
	EntityCellEntityCall_FrameSyncReportBase* componentFrameSync;

	EntityCellEntityCall_AvatarBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_AvatarBase();
};
