/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class FrameSyncReport : public FrameSyncReportBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "EntityComponent.h"
#include "KBETypes.h"
#include "ServerErrorDescrs.h"
#include "EntityCallFrameSyncReportBase.h"

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/FrameSyncReport.def
class KBENGINEPLUGINS_API FrameSyncReportBase : public EntityComponent
{
public:
	EntityBaseEntityCall_FrameSyncReportBase* pBaseEntityCall;
	EntityCellEntityCall_FrameSyncReportBase* pCellEntityCall;

	int8 seatNo;
	virtual void onSeatNoChanged(int8 oldValue) {}

	virtual void onFrameMessage(const FS_FRAME_DATA& arg1) = 0; 

	void createFromStream(MemoryStream& stream) override;

	void onRemoteMethodCall(uint16 methodUtype, MemoryStream& stream) override;
	void onUpdatePropertys(uint16 propUtype, MemoryStream& stream, int maxCount) override;
	void callPropertysSetMethods() override;

	FrameSyncReportBase();
	virtual ~FrameSyncReportBase();

};

