/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class FrameSync : public FrameSyncBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "EntityComponent.h"
#include "KBETypes.h"
#include "ServerErrorDescrs.h"
#include "EntityCallFrameSyncBase.h"

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/FrameSync.def
class KBENGINEPLUGINS_API FrameSyncBase : public EntityComponent
{
public:
	EntityBaseEntityCall_FrameSyncBase* pBaseEntityCall;
	EntityCellEntityCall_FrameSyncBase* pCellEntityCall;



	void createFromStream(MemoryStream& stream) override;

	void onRemoteMethodCall(uint16 methodUtype, MemoryStream& stream) override;
	void onUpdatePropertys(uint16 propUtype, MemoryStream& stream, int maxCount) override;
	void callPropertysSetMethods() override;

	FrameSyncBase();
	virtual ~FrameSyncBase();

};

