/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"


// defined in */scripts/entity_defs/types.xml

typedef uint8 UINT8;

typedef uint16 UINT16;

typedef uint64 UINT64;

typedef uint32 UINT32;

typedef int8 INT8;

typedef int16 INT16;

typedef int32 INT32;

typedef int64 INT64;

typedef FString STRING;

typedef FString KBE_UNICODE;

typedef float FLOAT;

typedef double DOUBLE;

typedef TArray<uint8> PYTHON;

typedef TArray<uint8> PY_DICT;

typedef TArray<uint8> PY_TUPLE;

typedef TArray<uint8> PY_LIST;

typedef TArray<uint8> ENTITYCALL;

typedef TArray<uint8> BLOB;

typedef FVector2D VECTOR2;

typedef FVector VECTOR3;

typedef FVector4 VECTOR4;

typedef int32 OBJECT_ID;

typedef uint8 BOOL;

typedef uint64 DBID;

typedef uint64 UID;

typedef int32 ENTITY_ID;

typedef uint8 ROLE_ID;

typedef int32 WEAPON_ID;

typedef FString KBE_NAME;

typedef uint8 TEAM_ID;

typedef uint32 SPACE_ID;

typedef uint32 ROOMPOSITION_ID;

typedef FVector POSITION3D;

typedef FVector DIRECTION3D;

typedef uint64 SPACE_KEY;

typedef int32 ROOMSTATE;

typedef uint32 FRAMEID;

typedef uint8 CMD_TYPE;

class KBENGINEPLUGINS_API AVATAR_INFOS
{
public:
	uint64 dbid;
	FString name;
	uint8 roleType;
	int32 weaponId;

	AVATAR_INFOS():
	dbid(0),
	name(),
	roleType(0),
	weaponId(0)
	{
	}

};

class KBENGINEPLUGINS_API AVATAR_INFOS_LIST
{
public:
	TArray<AVATAR_INFOS> values;

	AVATAR_INFOS_LIST():
	values()
	{
	}

};

class KBENGINEPLUGINS_API MATCHING_INFOS
{
public:
	int32 id;
	FString name;
	uint8 roleType;
	int32 weaponId;
	uint8 roomId;
	uint8 roomPosition;
	uint8 teamId;

	MATCHING_INFOS():
	id(0),
	name(),
	roleType(0),
	weaponId(0),
	roomId(0),
	roomPosition(0),
	teamId(0)
	{
	}

};

class KBENGINEPLUGINS_API MATCHING_INFOS_LIST
{
public:
	TArray<MATCHING_INFOS> values;

	MATCHING_INFOS_LIST():
	values()
	{
	}

};

class KBENGINEPLUGINS_API FS_ENTITY_DATA
{
public:
	int32 entityid;
	uint8 cmd_type;
	TArray<uint8> datas;

	FS_ENTITY_DATA():
	entityid(0),
	cmd_type(0),
	datas()
	{
	}

};

class KBENGINEPLUGINS_API FS_FRAME_DATA
{
public:
	uint32 frameid;
	TArray<FS_ENTITY_DATA> operation;

	FS_FRAME_DATA():
	frameid(0),
	operation()
	{
	}

};

class KBENGINEPLUGINS_API FS_FRAME_LIST
{
public:
	TArray<FS_FRAME_DATA> values;

	FS_FRAME_LIST():
	values()
	{
	}

};

