/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class OperationSync : public OperationSyncBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "EntityComponent.h"
#include "KBETypes.h"
#include "ServerErrorDescrs.h"
#include "EntityCallOperationSyncBase.h"

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/OperationSync.def
class KBENGINEPLUGINS_API OperationSyncBase : public EntityComponent
{
public:
	EntityBaseEntityCall_OperationSyncBase* pBaseEntityCall;
	EntityCellEntityCall_OperationSyncBase* pCellEntityCall;

	int8 seatNo;
	virtual void onSeatNoChanged(int8 oldValue) {}

	virtual void onFrameMessage(const FRAME_DATA& arg1) = 0; 

	void createFromStream(MemoryStream& stream) override;

	void onRemoteMethodCall(uint16 methodUtype, MemoryStream& stream) override;
	void onUpdatePropertys(uint16 propUtype, MemoryStream& stream, int maxCount) override;
	void callPropertysSetMethods() override;

	OperationSyncBase();
	virtual ~OperationSyncBase();

};

