/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Avatar : AvatarBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avatar.def
	// Please inherit and implement "class Avatar : AvatarBase"
	public abstract class AvatarBase : Entity
	{
		public EntityBaseEntityCall_AvatarBase baseEntityCall = null;
		public EntityCellEntityCall_AvatarBase cellEntityCall = null;

		public FrameSyncReportBase componentFrameSync = null;
		public SByte gameStateC = 0;
		public virtual void onGameStateCChanged(SByte oldValue) {}
		public Byte modelID = 0;
		public virtual void onModelIDChanged(Byte oldValue) {}
		public float moveSpeed = 6.5f;
		public virtual void onMoveSpeedChanged(float oldValue) {}
		public string name = "";
		public virtual void onNameChanged(string oldValue) {}
		public Byte roleType = 0;
		public virtual void onRoleTypeChanged(Byte oldValue) {}
		public SByte state = 0;
		public virtual void onStateChanged(SByte oldValue) {}
		public Byte teamID = 0;
		public virtual void onTeamIDChanged(Byte oldValue) {}
		public Int32 weaponID = 0;
		public virtual void onWeaponIDChanged(Int32 oldValue) {}

		public abstract void onEnding(); 
		public abstract void onPlayerQuitMatch(Int32 arg1); 
		public abstract void onReadyForBattle(); 
		public abstract void onResPlayersInfo(MATCHING_INFOS_LIST arg1); 
		public abstract void onReturnHalls(); 
		public abstract void onStatisticalResult(Byte arg1, float arg2); 
		public abstract void onTeamMateChange(); 

		public AvatarBase()
		{
			foreach (System.Reflection.Assembly ass in AppDomain.CurrentDomain.GetAssemblies())
			{
				Type entityComponentScript = ass.GetType("KBEngine.FrameSyncReport");
				if(entityComponentScript != null)
				{
					componentFrameSync = (FrameSyncReportBase)Activator.CreateInstance(entityComponentScript);
					componentFrameSync.owner = this;
					componentFrameSync.entityComponentPropertyID = 15;
				}
			}

			if(componentFrameSync == null)
				throw new Exception("Please inherit and implement, such as: \"class FrameSyncReport : FrameSyncReportBase\"");

		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_AvatarBase(id, className);
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_AvatarBase(id, className);
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void attachComponents()
		{
			componentFrameSync.onAttached(this);
		}

		public override void detachComponents()
		{
			componentFrameSync.onDetached(this);
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Avatar"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.useMethodDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
				methodUtype = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					case 15:
						componentFrameSync.onRemoteMethodCall(methodUtype, stream);
						break;
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				case 14:
					onEnding();
					break;
				case 10:
					Int32 onPlayerQuitMatch_arg1 = stream.readInt32();
					onPlayerQuitMatch(onPlayerQuitMatch_arg1);
					break;
				case 12:
					onReadyForBattle();
					break;
				case 9:
					MATCHING_INFOS_LIST onResPlayersInfo_arg1 = ((DATATYPE_MATCHING_INFOS_LIST)method.args[0]).createFromStreamEx(stream);
					onResPlayersInfo(onResPlayersInfo_arg1);
					break;
				case 13:
					onReturnHalls();
					break;
				case 15:
					Byte onStatisticalResult_arg1 = stream.readUint8();
					float onStatisticalResult_arg2 = stream.readFloat();
					onStatisticalResult(onStatisticalResult_arg1, onStatisticalResult_arg2);
					break;
				case 11:
					onTeamMateChange();
					break;
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Avatar"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				UInt16 _t_child_utype = 0;

				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
						_t_child_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
						_t_child_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype == 0)
				{
					prop = pdatas[_t_child_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						case 15:
							componentFrameSync.onUpdatePropertys(_t_child_utype, stream, -1);
							break;
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 15:
						componentFrameSync.createFromStream(stream);
						break;
					case 40001:
						Vector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 11:
						SByte oldval_gameStateC = gameStateC;
						gameStateC = stream.readInt8();

						if(prop.isBase())
						{
							if(inited)
								onGameStateCChanged(oldval_gameStateC);
						}
						else
						{
							if(inWorld)
								onGameStateCChanged(oldval_gameStateC);
						}

						break;
					case 13:
						Byte oldval_modelID = modelID;
						modelID = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onModelIDChanged(oldval_modelID);
						}
						else
						{
							if(inWorld)
								onModelIDChanged(oldval_modelID);
						}

						break;
					case 8:
						float oldval_moveSpeed = moveSpeed;
						moveSpeed = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMoveSpeedChanged(oldval_moveSpeed);
						}
						else
						{
							if(inWorld)
								onMoveSpeedChanged(oldval_moveSpeed);
						}

						break;
					case 3:
						string oldval_name = name;
						name = stream.readUnicode();

						if(prop.isBase())
						{
							if(inited)
								onNameChanged(oldval_name);
						}
						else
						{
							if(inWorld)
								onNameChanged(oldval_name);
						}

						break;
					case 40000:
						Vector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 4:
						Byte oldval_roleType = roleType;
						roleType = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onRoleTypeChanged(oldval_roleType);
						}
						else
						{
							if(inWorld)
								onRoleTypeChanged(oldval_roleType);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					case 9:
						SByte oldval_state = state;
						state = stream.readInt8();

						if(prop.isBase())
						{
							if(inited)
								onStateChanged(oldval_state);
						}
						else
						{
							if(inWorld)
								onStateChanged(oldval_state);
						}

						break;
					case 6:
						Byte oldval_teamID = teamID;
						teamID = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onTeamIDChanged(oldval_teamID);
						}
						else
						{
							if(inWorld)
								onTeamIDChanged(oldval_teamID);
						}

						break;
					case 5:
						Int32 oldval_weaponID = weaponID;
						weaponID = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onWeaponIDChanged(oldval_weaponID);
						}
						else
						{
							if(inWorld)
								onWeaponIDChanged(oldval_weaponID);
						}

						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["Avatar"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			componentFrameSync.callPropertysSetMethods();

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			SByte oldval_gameStateC = gameStateC;
			Property prop_gameStateC = pdatas[5];
			if(prop_gameStateC.isBase())
			{
				if(inited && !inWorld)
					onGameStateCChanged(oldval_gameStateC);
			}
			else
			{
				if(inWorld)
				{
					if(prop_gameStateC.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onGameStateCChanged(oldval_gameStateC);
					}
				}
			}

			Byte oldval_modelID = modelID;
			Property prop_modelID = pdatas[6];
			if(prop_modelID.isBase())
			{
				if(inited && !inWorld)
					onModelIDChanged(oldval_modelID);
			}
			else
			{
				if(inWorld)
				{
					if(prop_modelID.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onModelIDChanged(oldval_modelID);
					}
				}
			}

			float oldval_moveSpeed = moveSpeed;
			Property prop_moveSpeed = pdatas[7];
			if(prop_moveSpeed.isBase())
			{
				if(inited && !inWorld)
					onMoveSpeedChanged(oldval_moveSpeed);
			}
			else
			{
				if(inWorld)
				{
					if(prop_moveSpeed.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMoveSpeedChanged(oldval_moveSpeed);
					}
				}
			}

			string oldval_name = name;
			Property prop_name = pdatas[8];
			if(prop_name.isBase())
			{
				if(inited && !inWorld)
					onNameChanged(oldval_name);
			}
			else
			{
				if(inWorld)
				{
					if(prop_name.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onNameChanged(oldval_name);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

			Byte oldval_roleType = roleType;
			Property prop_roleType = pdatas[9];
			if(prop_roleType.isBase())
			{
				if(inited && !inWorld)
					onRoleTypeChanged(oldval_roleType);
			}
			else
			{
				if(inWorld)
				{
					if(prop_roleType.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onRoleTypeChanged(oldval_roleType);
					}
				}
			}

			SByte oldval_state = state;
			Property prop_state = pdatas[10];
			if(prop_state.isBase())
			{
				if(inited && !inWorld)
					onStateChanged(oldval_state);
			}
			else
			{
				if(inWorld)
				{
					if(prop_state.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onStateChanged(oldval_state);
					}
				}
			}

			Byte oldval_teamID = teamID;
			Property prop_teamID = pdatas[11];
			if(prop_teamID.isBase())
			{
				if(inited && !inWorld)
					onTeamIDChanged(oldval_teamID);
			}
			else
			{
				if(inWorld)
				{
					if(prop_teamID.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onTeamIDChanged(oldval_teamID);
					}
				}
			}

			Int32 oldval_weaponID = weaponID;
			Property prop_weaponID = pdatas[12];
			if(prop_weaponID.isBase())
			{
				if(inited && !inWorld)
					onWeaponIDChanged(oldval_weaponID);
			}
			else
			{
				if(inWorld)
				{
					if(prop_weaponID.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onWeaponIDChanged(oldval_weaponID);
					}
				}
			}

		}
	}
}