/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avatar.def
	public class EntityBaseEntityCall_AvatarBase : EntityCall
	{
		public EntityBaseEntityCall_FrameSyncReportBase componentFrameSync = null;

		public EntityBaseEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			componentFrameSync = new EntityBaseEntityCall_FrameSyncReportBase(15, id);
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void endOfStatistics()
		{
			Bundle pBundle = newCall("endOfStatistics", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void enterStartGame()
		{
			Bundle pBundle = newCall("enterStartGame", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void registerHalls()
		{
			Bundle pBundle = newCall("registerHalls", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void statisticalResult(Byte arg1, float arg2)
		{
			Bundle pBundle = newCall("statisticalResult", 0);
			if(pBundle == null)
				return;

			bundle.writeUint8(arg1);
			bundle.writeFloat(arg2);
			sendCall(null);
		}

		public void weaponChanged(Int32 arg1)
		{
			Bundle pBundle = newCall("weaponChanged", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AvatarBase : EntityCall
	{
		public EntityCellEntityCall_FrameSyncReportBase componentFrameSync = null;

		public EntityCellEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			componentFrameSync = new EntityCellEntityCall_FrameSyncReportBase(15, id);
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
